-- create_ai_events_table.sql
-- Run this in Supabase SQL editor or via psql to create the ai_events table

create table if not exists ai_events (
  id bigint generated by default as identity primary key,
  user_id text,
  event_type text,
  module text,
  action text,
  lang text,
  payload jsonb,
  created_at timestamptz default now()
);

create index if not exists idx_ai_events_created_at on ai_events(created_at);
create index if not exists idx_ai_events_user_id on ai_events(user_id);
